version: '3'

services:

  app:
    build:
      context: .
      dockerfile: compose/fast_api/app/Dockerfile
    container_name: "traxion-passenger-app"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/app
    ports:
      - 8001:8000
    networks:
      - reservation-app-net
    command: /start_app.sh

  worker-app:
    build:
      context: .
      dockerfile: compose/fast_api/worker/Dockerfile
    container_name: "traxion-passenger-worker-app"
    networks:
      - reservation-app-net
    volumes:
      - .:/app
    command: /start_worker.sh

  postgres:
    image: postgres:12.3
    container_name: "traxion-passenger-db"
    networks:
      - reservation-app-net
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data:Z
    env_file:
      - .env
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5434:5432"

networks:
  reservation-app-net:
    external: true